import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin-ext"] });

import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  if (process.env.NEXT_PUBLIC_IS_DEVELOPMENT) {
    return (
      <html>
        <body>
          <main className="h-screen w-full flex items-center justify-center">
            <p className="text-sm">strona w budowie</p>
          </main>
        </body>
      </html>
    );
  } else {
    return (
      <html lang="pl">
        <body className={inter.className}>
          <Header />
          <main>{children}</main>
          {/* <Footer /> */}
        </body>
      </html>
    );
  }
}
